Ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'Ecommerce'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product_list'),
    path('products/<int:pk>/', views.product_detail, name='product_detail'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/<int:pk>', views.customer_detail, name='customer_detail'),

]

PlpProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Ecommerce/' , include('Ecommerce.urls')),
]

Ecommerce/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    Availability = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name
    
    
class Customer(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

    

Ecommerce/views.py
from django.shortcuts import get_object_or_404, render
from .models import Product, Customer

def home(request):
    return render(request, 'Ecommerce/home.html')

def product_list(request):
    products = Product.objects.all()
    context = {
        'products' : products
    }
    return render(request,'Ecommerce/product_list.html',context)

def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'product' : product
    }
    return render(request, 'Ecommerce/product_detail.html', context)

def customer_list(request):
    customers = Customer.objects.all()
    context = {
        'customers' : customers
    }
    return render(request,'Ecommerce/customer_list.html', context)

def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    context = {
        'customer' : customer
    }
    return render(request, 'Ecommerce/customer_detail.html', context)

Ecommerce/templates/Ecommerce/customer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Details</title>
</head>
<body>
    <h1>Customer Details</h1>
    <div class="container">


        <div class="customer-details">
            <h3> {{customer.first_name}}{{customer.last_name}} </h3>
            <p><strong>Phone: </strong>{{customer.phone}}</p>
            <p><strong>Address: </strong>{{customer.address}}</p>
            <p><strong>Joined on: </strong>{{customer.created_at}}</p>

        </div>
       <a href="{% url 'Ecommerce:customer_list' %}" class="back-link">Back to Customer List</a> 
    </div>
</body>

</html>

Ecommerce/templates/Ecommerce/customer_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Ecommerce/styles.css' %}" />
    <title>Customer List</title>
</head>
<body>
    <h1>Customer List</h1>


    <ul>
        {% for customer in customers %}
        <li>
            <a href="{% url 'Ecommerce:customer_detail' customer.pk %}">
                {{customer.first_name}}{{customer.last_name}}{{customer.email}}
            </a>
        </li>
        {% endfor %}
    </ul>
</body>
<!---- <a href="{% url 'Ecommerce:customer_list' %}"> Back to Customer List</a>

</html>

Ecommerce/templates/Ecommerce/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Ecommerce/styles.css' %}" />
    <title>Ecommerce</title>
</head>
<body>
    <h1>Welcome to our E-commerce Website</h1>
    <nav>
        <ul>
            <li><a href="{% url 'Ecommerce:product_list %'}">Products</a></li>
            <li><a href="{% url 'Ecommerce:customer_list %'}">Customers</a></li>
        </ul>
    </nav>
</body>

</html>

Ecommerce/templates/Ecommerce/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{product.name}}</title>
</head>
<body>



<ul>
    {% for product in product %}
    <li>
        <h2>{{product.name}} </h2>
        <p> {{product.description}}</p>
        <p> Price: $.{{product.price}}</p>
        <img src="{{product.image.url}}" alt="{{product.name}}" />
        <p> Available: {{product.available|yesno:"Yes,No"}} </p>
    </li>
    {% endfor %}
</ul>
<!-- <a href="{% url 'Ecommerce:product_list' %}" class="back-link">Back to Product List</a> -->
</body>
</html>

Ecommerce/templates/Ecommerce/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>
<body>
 <h1>Products</h1>
 <ul>
    {% for product in products %}
    <li>
        <h2>{{product.name}} </h2>
        <p> {{product.description}}</p>
        <p> Price: $. {{product.price}}</p>
        <img src="{{product.image.url}}" alt="{{product.name}}"/>
        <p> Available: {{product.available|yesno:"Yes,No"}} </p>
    </li>
    {% endfor %}
 </ul>

</body>
</html>